#!/bin/bash

link_config() {
    local name="$1"
    local src="$(pwd)/.config/$name"
    local dest="$HOME/.config/$name"

    mkdir -p "$HOME/.config"

    if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
        return
    fi

    if [ -e "$dest" ] || [ -L "$dest" ]; then
        mv "$dest" "$dest.backup-$(date +%Y%m%d%H%M%S)"
    fi

    ln -s "$src" "$dest"
}

#### ----------- setup dotfiles ---------

git submodule init
git submodule update
make gnome-terminal-config-restore 
link_config fish
link_config nvim
link_config alacritty
link_config ghostty
link_config tmux
ln -s $(pwd)/.config/spotifyd ~/.config

#### --------- install tools ---------

# terminal utils
sudo dnf install -y neovim fd-find ripgrep fish starship util-linux-user gh golang tmux &

# oh my fish
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish


#### ----------- extra tools -------------

# multimedia
sudo dnf groupupdate core -y
sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
sudo dnf groupupdate sound-and-video -y
sudo dnf install -y mpv yt-dlp



#### ----------- setup shell ------------

sudo chsh $USER -s /usr/bin/fish
