#!/bin/bash


#### ----------- setup dotfiles ---------

mkdir .tmp
cd .tmp
git clone https://github.com/aniketfuryrocks/dotfiles
cd dotfiles/.config
git pull
ln -s $(pwd)/alacritty ~/.config
rm -rf ~/.config/fish
ln -s $(pwd)/fish ~/.config
ln -s $(pwd)/nvim ~/.config


#### --------- install tools ---------

# sync repos

sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf upgrade -y

# rust
sudo dnf install @development-tools
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
nvm install node

# sdkman
curl -s "https://get.sdkman.io" | bash 

# terminal utils
sudo dnf install -y neovim fd-find ripgrep fish starship util-linux-user &

# vim plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# oh my fish
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish



#### ------------ rust tools ------------

# deps
sudo dnf install -y pulseaudio-libs-devel libxcb-devel openssl-devel ncurses-devel dbus-devel

# tools
cargo install ncspot &
cargo install topgrade &
cargo install gxib &
cargo install cargo-expand &
cargo install cargo-edit &
cargo install cargo-update &


#### ----------- extra tools -------------

# multimedia
sudo dnf groupupdate core -y
sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y
sudo dnf groupupdate sound-and-video -y
sudo dnf install -y mpv yt-dlp



#### ----------- setup shell ------------

sudo chsh $USER -s /usr/bin/fish

