#!/bin/bash

red_echo() {
    echo ""
    echo -e "\x1b[1;31m $1\e[0m"
    echo ""
}

link_config() {
    local name="$1"
    local src="$(pwd)/.config/$name"
    local dest="$HOME/.config/$name"

    mkdir -p "$HOME/.config"

    if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
        return
    fi

    if [ -e "$dest" ] || [ -L "$dest" ]; then
        mv "$dest" "$dest.backup-$(date +%Y%m%d%H%M%S)"
    fi

    ln -s "$src" "$dest"
}

#### ----------- setup dotfiles ---------

red_echo "initializing dot files"
git submodule init
git submodule update
link_config fish
link_config nvim
link_config alacritty
link_config ghostty
link_config tmux

#### --------- git config --------------

red_echo "configuring git"
git config --global user.name "aniketfuryrocks"
git config --global user.email "contact@aniketprajapati.me" 
git config --global core.editor "nvim"
git config --global init.defaultBranch main
git config --global credential.helper store
git config --list


#### --------- install tools ---------

red_echo "upgrading system"
sudo dnf upgrade -y
red_echo "installing terminal utils"
sudo dnf install neovim fish util-linux-user fzf gh z golang tmux -y
red_echo "installing essential compilers and linkers"
sudo dnf install @development-tools mold gcc g++ cmake clang openssl-devel meson -y
red_echo "installing lazygit"
sudo dnf copr enable atim/lazygit -y
sudo dnf install lazygit -y


#### --------- shell ---------

red_echo "changing default shell to fish"
sudo chsh ${USER} -s /usr/bin/fish
red_echo "installing omf"
omf_install=$(mktemp)
curl -fsSL https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install -o "$omf_install"
fish "$omf_install" --noninteractive
rm "$omf_install"
red_echo "installing omf plugins"
fish -c 'omf install bass fzf nvm z'



#### --------- imp languages ---------

red_echo "installing rust"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
mkdir -p ~/.cargo 
cp ./config.toml ~/.cargo/ 

red_echo "installing nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
fish -c 'nvm install node'

red_echo "installing bun"
curl -fsSL https://bun.sh/install | bash


#### ------------ rust tools ------------

red_echo "installing rust tools"
fish -c 'cargo install cargo-expand cargo-edit cargo-update cargo-watch --locked'
fish -c 'cargo install eza ripgrep fd-find starship bat topgrade miniserve --locked' 
