# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j8"
USE="-kde -qt5 -systemd -quicktime -plasma -widgets gtk gtk3 gtk4 gnome screencast openrc policykit dbus ssl udev udisks unicode upower vim-syntax wifi video sound zip gnome-keyring networkmanager pcre32 wayland xwayland gles2 gles3 vulkan egl theora bluetooth mp3 mp4 mpeg png introspection tray systray fish-completion"
ACCEPT_LICENSE="*"
# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
GENTOO_MIRRORS="https://download.nus.edu.sg/mirror/gentoo/"
# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
GRUB_PLATFORMS="efi-64"
