[global]
username = "ehlo8s1iwljsyccatygh07wo0"

# Your Spotify account password.
# secret-tool store --label='aniketfuryrocks' application rust-keyring service spotifyd username "ehlo8s1iwljsyccatygh07wo0"
bitrate = 320
use_keyring = true
use_mpris = true
device_type = "computer"
device_name = "spotifyd@fedora"
