#! /bin/sh

# compositor
pkill -x picom
picom &

# notifications
pkill -x dunst
dunst &

# wallpaper
nitrogen --restore

# dock
pkill -x plank
plank &

# tray icons
pkill -x cbatticon
cbatticon &

pkill -x nm-applet
nm-applet &

pkill -x optmius-manager-qt
optimus-manager-qt &

pkill -x pasystray
pasystray & 

pkill -x blueman-tray
blueman-tray &

pkill -x mictray
mictray &

# kde connect
pkill -x kdeconnect-indicator
kdeconnect-indicator &

# desktops
bspc monitor -d 1 2 3 4 5
if [[ $(xrandr -q | grep 'HDMI-1-1 connected') ]]; then
    bspc monitor eDP-1-1 -d 6 7 8 9 0
fi

bspc config border_width         1
bspc config window_gap          15

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# dock
bspc rule -a Plank layer=above manage=on border=off

# bar
~/.config/polybar/launch.sh
